import { RoomData } from './types';

export const initialMockRooms: RoomData[] = [
  {
    roomId: 'sala-1',
    roomName: 'Sala 1',
    serviceType: 'Consulta & Avaliação',
    status: 'livre',
    capacity: 2,
    equipment: ['Secretária Clínica', 'Poltrona de Relaxamento', 'Computador de Fichas'],
  },
  {
    roomId: 'sala-2',
    roomName: 'Sala 2',
    serviceType: 'Terapia Ocupacional',
    status: 'ocupada',
    capacity: 3,
    equipment: ['Material Sensorial', 'Mesa Ergonómica', 'Poltrona Conforto'],
    currentClientName: 'João Silva',
    therapistName: 'Terapeuta Ana',
    sessionStart: new Date(new Date().getTime() - 40 * 60000).toISOString(),
    sessionEnd: new Date(new Date().getTime() + 20 * 60000).toISOString(),
  },
  {
    roomId: 'sala-3',
    roomName: 'Sala 3',
    serviceType: 'Yoga Nidra & Relaxamento',
    status: 'ocupada',
    capacity: 2,
    equipment: ['Tapetes Premium', 'Sistema de Som Binaural', 'Iluminação Suave'],
    currentClientName: 'Maria Costa',
    therapistName: 'Bárbara Carvalho',
    sessionStart: new Date(new Date().getTime() - 15 * 60000).toISOString(),
    sessionEnd: new Date(new Date().getTime() + 35 * 60000).toISOString(),
  },
  {
    roomId: 'sala-4',
    roomName: 'Sala 4',
    serviceType: 'Avaliação QEEG & Diagnóstico',
    status: 'livre',
    capacity: 2,
    equipment: ['Amplificador EEG 24 Canais', 'Cap QEEG', 'Ecrã Duplo Diagnóstico'],
  },
  {
    roomId: 'sala-5',
    roomName: 'Sala 5',
    serviceType: 'Neurofeedback (Gabinete A)',
    status: 'a_terminar',
    capacity: 2,
    equipment: ['BrainMaster Discovery 24E', '2 Marquesas Reclináveis', 'Monitores de Biofeedback'],
    currentClientName: 'Pedro Martins',
    therapistName: 'Bárbara Carvalho',
    sessionStart: new Date(new Date().getTime() - 53 * 60000).toISOString(),
    sessionEnd: new Date(new Date().getTime() + 7 * 60000).toISOString(),
  },
  {
    roomId: 'sala-6',
    roomName: 'Sala 6',
    serviceType: 'Neurofeedback (Gabinete B)',
    status: 'higienizacao',
    capacity: 2,
    equipment: ['BrainMaster Atlantis 4X', '2 Marquesas Reclináveis', 'Ecrãs de Feedback Visual'],
    cleaningUntil: new Date(new Date().getTime() + 8 * 60000).toISOString(),
  }
];
