// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phusjzzsqrtymjjnllgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodXNqenpzcXJ0eW1qam5sbGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTkyNDcsImV4cCI6MjA2MTY5NTI0N30.pkyczfP43xf8iRU9u2OoyqnVCDKdS1IBbpHzy9-EFMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// A área de marketing autentica-se por token (sem sessão Supabase Auth).
// O token é enviado no header de cada pedido REST e validado nas políticas
// RLS (função current_marketing_role) — ver fix_marketing_security.sql.
// O admin também envia o seu token (x-admin-token), permitindo ler leads,
// campanhas e lead_compra na app geral (validado em current_marketing_role).
const authedFetch: typeof fetch = (input, init = {}) => {
  try {
    const headers = new Headers(init.headers);

    const marketingSessionStr = localStorage.getItem('marketing_session');
    if (marketingSessionStr) {
      const session = JSON.parse(marketingSessionStr);
      if (session?.accessToken && session?.marketingEmail) {
        headers.set('x-marketing-token', String(session.accessToken));
        headers.set('x-marketing-email', String(session.marketingEmail));
      }
    }

    const adminSessionStr = localStorage.getItem('admin_session');
    if (adminSessionStr) {
      const adminSession = JSON.parse(adminSessionStr);
      if (adminSession?.token) {
        headers.set('x-admin-token', String(adminSession.token));
      }
    }

    return fetch(input, { ...init, headers });
  } catch {
    // sessão inválida/indisponível: seguir sem headers
    return fetch(input, init);
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: authedFetch,
  },
});

// Cliente Supabase com contexto anónimo garantido (sem sessão de utilizador anexada).
// Permite que operações em tabelas públicas de marketing funcionem mesmo se
// a sessão do utilizador autenticado encontrar políticas RLS restritivas.
export const supabaseAnon = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
});

