// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phusjzzsqrtymjjnllgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodXNqenpzcXJ0eW1qam5sbGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTkyNDcsImV4cCI6MjA2MTY5NTI0N30.pkyczfP43xf8iRU9u2OoyqnVCDKdS1IBbpHzy9-EFMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);