// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phusjzzsqrtymjjnllgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodXNqenpzcXJ0eW1qam5sbGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTkyNDcsImV4cCI6MjA2MTY5NTI0N30.pkyczfP43xf8iRU9u2OoyqnVCDKdS1IBbpHzy9-EFMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: {
      getItem: (key) => {
        const value = localStorage.getItem(key);
        if (!value) return null;
        
        try {
          const parsed = JSON.parse(value);
          if (parsed.expires_at && parsed.expires_at < Date.now()) {
            localStorage.removeItem(key);
            return null;
          }
          return value;
        } catch {
          return null;
        }
      },
      setItem: (key, value) => {
        try {
          const parsed = JSON.parse(value);
          if (parsed.expires_at) {
            // Set expiration to 7 days from now
            parsed.expires_at = Date.now() + 7 * 24 * 60 * 60 * 1000;
          }
          localStorage.setItem(key, JSON.stringify(parsed));
        } catch {
          localStorage.setItem(key, value);
        }
      },
      removeItem: (key) => localStorage.removeItem(key)
    }
  }
}); 